# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4f4f14b1caf6f58e3f4ebd8d9270e6801bd36cc2334d82228b5bc8d6c1fcbf4cd734ecb87db2ca1a50c340bc677b6b0f0401b254a1348cb1093b73eaa270b7

test:
  secret_key_base: 013543e681200a9a5006de66297092585eaea0f66a74eeef8b27a50f7332fbf010d204f6ffa724a98e0c2012294ad028d97ad16555d07edf45095b6231bdc8f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
